version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/netcard-backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/netcard-app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
